/**
 * Mock Data de respaldo para Paneles de Productora y Artista.
 * Se utiliza como fallback automático si el backend aún no dispone de las rutas o tablas de métricas.
 */

export const MOCK_PRODUCER_DASHBOARD = {
  metrics: [
    {
      id: "prod-1",
      title: "ENTRADAS VENDIDAS",
      value: "1.420",
      change: "+18.4%",
      isPositive: true,
      icon: "🎫",
      subtext: "vs. mes anterior",
    },
    {
      id: "prod-2",
      title: "RECAUDACIÓN TOTAL",
      value: "$ 8.520.000",
      change: "+24.1%",
      isPositive: true,
      icon: "💰",
      subtext: "pesos argentinos",
    },
    {
      id: "prod-3",
      title: "SHOWS ACTIVOS",
      value: "4",
      change: "+2 nuevos",
      isPositive: true,
      icon: "🔥",
      subtext: "en cartelera",
    },
    {
      id: "prod-4",
      title: "ASISTENCIA PROMEDIO",
      value: "88%",
      change: "+5%",
      isPositive: true,
      icon: "📈",
      subtext: "capacidad total",
    },
  ],
  events: [
    {
      id: "evt-prod-101",
      title: "TUCUMÁN PUNK FEST VI",
      date: "15 AGO 2026",
      venue: "El Galpón Cultural",
      city: "San Miguel de Tucumán",
      ticketsSold: 450,
      totalCapacity: 500,
      revenue: 2700000,
      status: "publicado",
      image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "evt-prod-102",
      title: "NOCHE SUBTERRÁNEA HARDCORE",
      date: "02 SEP 2026",
      venue: "Magic Music Box",
      city: "San Miguel de Tucumán",
      ticketsSold: 280,
      totalCapacity: 350,
      revenue: 1680000,
      status: "publicado",
      image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "evt-prod-103",
      title: "FESTIVAL METAL NORTE II",
      date: "18 SEP 2026",
      venue: "Club Sportivo Patria",
      city: "Tafí Viejo",
      ticketsSold: 690,
      totalCapacity: 800,
      revenue: 4140000,
      status: "publicado",
      image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80",
    },
  ],
};

export const MOCK_ARTIST_DASHBOARD = {
  metrics: [
    {
      id: "art-1",
      title: "SEGUIDORES TOTALES",
      value: "1.840",
      change: "+125 esta semana",
      isPositive: true,
      icon: "⚡",
      subtext: "comunidad activa",
    },
    {
      id: "art-2",
      title: "REPRODUCCIONES DEMO",
      value: "45.800",
      change: "+3.2k escuchas",
      isPositive: true,
      icon: "🎵",
      subtext: "en la plataforma VOY",
    },
    {
      id: "art-3",
      title: "FECHAS CONFIRMADAS",
      value: "3",
      change: "Próximos 60 días",
      isPositive: true,
      icon: "🎸",
      subtext: "shows programados",
    },
    {
      id: "art-4",
      title: "ENGAGEMENT FANS",
      value: "94%",
      change: "Muy alto",
      isPositive: true,
      icon: "🤘",
      subtext: "interacción en eventos",
    },
  ],
  upcomingEvents: [
    {
      id: "evt-art-201",
      title: "TUCUMÁN PUNK FEST VI",
      date: "15 AGO 2026 - 22:00 HS",
      venue: "El Galpón Cultural",
      city: "San Miguel de Tucumán",
      status: "confirmado",
      image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=600&q=80",
    },
    {
      id: "evt-art-202",
      title: "NEON SYNTH SESSION",
      date: "20 AGO 2026 - 01:00 HS",
      venue: "Club Isabel",
      city: "Yerba Buena",
      status: "confirmado",
      image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=600&q=80",
    },
  ],
};
